const Map<String, String> sdgMap = {
  "01": "SDG 01: No Poverty",
  "02": "SDG 02: Zero Hunger",
  "03": "SDG 03: Good Health and Well-being",
  "04": "SDG 04: Quality Education",
  "05": "SDG 05: Gender Equality",
  "06": "SDG 06: Clean Water and Sanitation",
  "07": "SDG 07: Affordable and Clean Energy",
  "08": "SDG 08: Decent Work and Economic Growth",
  "09": "SDG 09: Industry, Innovation and Infrastructure",
  "10": "SDG 10: Reduced Inequality",
  "11": "SDG 11: Sustainable Cities and Communities",
  "12": "SDG 12: Responsible Consumption and Production",
  "13": "SDG 13: Climate Action",
  "14": "SDG 14: Life Below Water",
  "15": "SDG 15: Life on Land",
  "16": "SDG 16: Peace and Justice Strong Institutions",
  "17": "SDG 17: Partnerships to achieve the Goal",
};